default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: rendezvous

test:
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: rendezvous
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: <%= ENV['MYSQL_SOCKET'] %>
